### ISSUE TITLE
Press F then crash

### ISSUE THREAD

**Issue by andrewfader** [alievk/avatarify#60] opened 2020-04-18 17:53 UTC
```./run.sh     
0: ./avatars/eminem.jpg
1: ./avatars/jobs.jpg
2: ./avatars/mona.jpg
3: ./avatars/obama.jpg
4: ./avatars/potter.jpg
5: ./avatars/ronaldo.png
6: ./avatars/schwarzenegger.png
load checkpoints..
cam_fomm.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:2503: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
1660 : 123
2184 : 123
115 : 123
Taking new frame!
1477 : 115
101 : 115
Taking new frame!
2636 : 101
90 : 101
Taking new frame!
2052 : 2986
Taking new frame!
2066 : 1682
1970 : 1682
89 : 1682
Taking new frame!
92 : 89
87 : 89
Taking new frame!
2184 : 87
1611 : 87
2166 : 87
86 : 87
Taking new frame!
2886 : 86
93 : 86
90 : 86
90 : 86
96 : 86
1940 : 86
1958 : 86
115 : 86
112 : 86
7766 : 86
105 : 86
/home/andrew/.local/lib/python3.8/site-packages/face_alignment/detection/sfd/bbox.py:61: RuntimeWarning: invalid value encountered in less_equal
  inds = np.where(ovr <= thresh)[0]
Traceback (most recent call last):
  File "cam_fomm.py", line 263, in <module>
    if is_new_frame_better(fa, avatar, frame, device):
  File "cam_fomm.py", line 88, in is_new_frame_better
    new_kp = get_frame_kp(fa, driving)
  File "cam_fomm.py", line 64, in get_frame_kp
    kp_landmarks = fa.get_landmarks(255 * image)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/api.py", line 141, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/api.py", line 187, in get_landmarks_from_image
    inp = crop(image, center, scale)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/utils.py", line 130, in crop
    newImg = cv2.resize(newImg, dsize=(int(resolution), int(resolution)),
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

**Comment by andrewfader** [comment] 2020-04-18 18:01
Gave it another whirl here
```
0: ./avatars/obama.jpg
load checkpoints..
cam_fomm.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:2705: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:2503: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  warnings.warn("Default upsampling behavior when mode={} is changed "
/home/andrew/.local/lib/python3.8/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
6529 : 5608
9835 : 5608
13045 : 5608
5782 : 5608
5499 : 5608
Taking new frame!
5691 : 30866
Taking new frame!
8239 : 6669
6200 : 6669
Taking new frame!
8891 : 5874
15793 : 5874
5532 : 5874
Taking new frame!
6633 : 6637
Taking new frame!
9897 : 5840
5446 : 5840
Taking new frame!
5314 : 6265
Taking new frame!
5757 : 5479
6715 : 5479
6717 : 5479
8489 : 5479
5751 : 5479
5497 : 5479
11970 : 5479
6743 : 5479
6732 : 5479
11912 : 5479
/home/andrew/.local/lib/python3.8/site-packages/face_alignment/detection/sfd/bbox.py:61: RuntimeWarning: invalid value encountered in less_equal
  inds = np.where(ovr <= thresh)[0]
Traceback (most recent call last):
  File "cam_fomm.py", line 263, in <module>
    if is_new_frame_better(fa, avatar, frame, device):
  File "cam_fomm.py", line 88, in is_new_frame_better
    new_kp = get_frame_kp(fa, driving)
  File "cam_fomm.py", line 64, in get_frame_kp
    kp_landmarks = fa.get_landmarks(255 * image)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/api.py", line 141, in get_landmarks
    return self.get_landmarks_from_image(image_or_path, detected_faces)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/api.py", line 187, in get_landmarks_from_image
    inp = crop(image, center, scale)
  File "/home/andrew/.local/lib/python3.8/site-packages/face_alignment/utils.py", line 130, in crop
    newImg = cv2.resize(newImg, dsize=(int(resolution), int(resolution)),
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

**Comment by alievk** [comment] 2020-04-18 18:11
Does this happen when it loses your face?

**Comment by andrewfader** [comment] 2020-04-21 02:14
I would say it never really totally worked correctly, but yeah kinda

**Comment by alievk** [comment] 2020-04-21 08:43
@andrewfader it is supposed to help finetuning face position & expression when the avatar has a pose diverse from a strait-looking-emotionless pose.

**Comment by JohanAR** [comment] 2021-01-13 08:24
Pretty sure this was caused by a bug in face-alignment, which should be fixed now. Please re-open or create a new issue if this still happens on latest master

**Closed by JohanAR** 2021-01-13 08:24 UTC
Labels: bug
