### ISSUE TITLE
neither of the windows, "cam" / "avatarify", appear

### ISSUE THREAD

**Issue by PeterKW** [alievk/avatarify#163] opened 2020-05-07 22:41 UTC
Windows "Run run_windows.bat. If installation was successful, two windows "cam" and "avatarify" will appear. Leave these windows open for the next installation steps. If there are multiple cameras (including virtual ones) in the system, you may need to select the correct one. Open scripts/settings_windows.bat and edit CAMID variable. CAMID is an index number of camera like 0, 1, 2, ..."

When I do this no errors appear on terminal but neither of the windows, "cam" / "avatarify", appear. Is there anything I can try?

**Comment by alievk** [comment] 2020-05-07 22:59
Could you provide more info? Any logs?

**Comment by guiyomh** [comment] 2020-05-10 10:30
I think I have the same problem with MAC. When I run the command `bash run_mac.sh --worker-host gpu_server_address` I had this output

```
Loading Predictor
Connected to gpu_server_address:5556
```

but I don't saw any cam's window or other windows launched. 

So I couldn't configure CamTwist :'(

I'm on OSX Catalina (10.15.4 - maybe missing permission)

**Comment by natgnah** [comment] 2020-05-11 02:13
i got error with cam. i had this output

```
[ WARN:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
[ WARN:1] global C:\projects\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 152, in <module>
    cap.start()
  File "C:\Users\natgnah_chen\avatarify\afy\videocaptureasync.py", line 44, in start
    raise RuntimeError(f"Failed to succesfully grab frame from the camera (timeout={WARMUP_TIMEOUT}s). Try to restart.")

```

**Comment by alievk** [comment] 2020-05-11 07:31
@guiyomh Mac can run only on remote GPU, since it's hardware is not powerful enough to run the neural network (need a NVIDIA GPU)

It's possible we will make it run on Mac smooth in the future.

**Comment by senegal8green** [comment] 2020-05-19 18:09
@PeterKW it seems your conda is not added to the windows PATH (try command 'conda --version' to check)

**Comment by clemsontiger** [comment] 2020-05-20 16:42
Having a similar problem. the cam window appears with my face, but the avatarify window does not ever appear. Where are the logs located?

 the miniconda prompt gives 2 warnings, but that's it:

`C:\Users\username\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

C:\Users\username\Miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
`
thanks

**Comment by clemsontiger** [comment] 2020-05-24 13:32
I reinstalled everything from scratch and I got it working, but terribly delayed/slow both my own face and the avatar

**Comment by alievk** [comment] 2020-05-25 08:07
Now you can run on Mac with a good speed using [Google Colab](https://colab.research.google.com/github/alievk/avatarify/blob/master/avatarify.ipynb)

**Comment by kafran** [comment] 2020-06-06 04:58
I have the same problem. Running on Ubuntu 18.04 with Colab GPU and neither the windows shows up. Tried everything, installed 18.04 v4l2loopback version 0.10, installed the 20.04 v4l2loopback version 0.12.3, installed the compiled one from /scripts/install.sh, changed v4l2loopback parameters.... nothing worked.

```
sudo v4l2-ctl -d /dev/video3 --all
Driver Info (not using libv4l2):
	Driver name   : v4l2 loopback
	Card type     : avatarify
	Bus info      : platform:v4l2loopback-000
	Driver version: 5.3.18
	Capabilities  : 0x85208002
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x05208002
		Video Output
		Video Memory-to-Memory
		Read/Write
		Streaming
		Extended Pix Format
Priority: 0
Video output: 0 (loopback in)
Format Video Output:
	Width/Height      : 0/0
	Pixel Format      : 'BGR4'
	Field             : None
	Bytes per Line    : 0
	Size Image        : 0
	Colorspace        : sRGB
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             :
Streaming Parameters Video Capture:
	Frames per second: 30.000 (30/1)
	Read buffers     : 2
Streaming Parameters Video Output:
	Frames per second: 30.000 (30/1)
	Write buffers    : 2

User Controls

                    keep_format 0x0098f900 (bool)   : default=0 value=0
              sustain_framerate 0x0098f901 (bool)   : default=0 value=0
                        timeout 0x0098f902 (int)    : min=0 max=100000 step=1 default=0 value=0
               timeout_image_io 0x0098f903 (bool)   : default=0 value=0

```

```
python afy/camera_selector.py
[1591419254.512844] Trying camera with id 0
[1591419255.388056] Trying camera with id 1
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[1591419255.388551] Camera with id 1 is not available
[1591419255.388623] Trying camera with id 2
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video2): can't open camera by index
[1591419255.388767] Camera with id 2 is not available
[1591419255.388822] Trying camera with id 3
[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[1591419255.388966] Camera with id 3 is not available
```

**Comment by YoungPharoah** [comment] 2020-10-23 21:54
Having the same problem, can anyone tell me where is the issue?

I have only my cam of my face showing, but no avatrify

![image](https://user-images.githubusercontent.com/43537619/97057198-6b546180-1593-11eb-98d4-72ac2f6f8e7a.png)

**Comment by alievk** [comment] 2020-12-28 09:46
You may want to check out OBS, they included virtual camera in the Mac version.
It works, I checked it.
https://cdn-fastly.obsproject.com/downloads/obs-mac-26.1.dmg

**Comment by JohanAR** [comment] 2021-01-13 08:58
Closing the issue since we never heard again from the original poster.

To anyone else who commented about their problems here: "neither of the windows appear" is just a symptom, and could be caused by anything. And since OP didn't provide details we have no way of knowing if your problem is related to theirs. If you are still having a problem, please either find another issue that matches yours (e.g. same error messages in log) or create a new one.

**Closed by JohanAR** 2021-01-13 08:58 UTC

**Comment by Tqq23** [comment] 2023-03-30 17:18
What do I do if only my cam appears and no avatarify or a second cam appears?

**Comment by west171888ydudh** [comment] 2023-04-04 03:32
> ```
> Users\username\avatarify\afy\predictor_local.py:34: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> 
> C:\Users\username\Miniconda3\envs\avatarify\lib\site-packages\torch\nn\functional.py:1332: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
>   warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
> ```
> 
> 
>     
> 
>   
> 
> after the torch warning appears, I can't do anything else, just a blinking cursor. if I hit Ctrl+C it ends the cam window, displays the following and asks if I want to terminate batch.

please i only i have one cam showing avatarify not showing

**Comment by west171888ydudh** [comment] 2023-04-04 03:38
only one cam appears avartarify does not

**Comment by west171888ydudh** [comment] 2023-04-04 04:01
### [/]
![16805808170927740608423034314532](https://user-images.githubusercontent.com/129818315/229683884-87831d9e-1768-4507-b003-8e49d08d07f3.jpg)
(url) please only on camera showing i need help

**Comment by west171888ydudh** [comment] 2023-04-04 04:01
> ### [/]
> ![16805808170927740608423034314532](https://user-images.githubusercontent.com/129818315/229683884-87831d9e-1768-4507-b003-8e49d08d07f3.jpg) (url) please only on camera showing i need help

avatarify not coming up

**Comment by JohanAR** [comment] 2023-04-04 05:51
@west171888ydudh you've followed the instructions on the screen?
